name: 自動擴充撩語

on:
  schedule:
    - cron: "0 6 */3 * *"  # 每 3 天的 6:00 UTC（台灣時間 14:00）
  workflow_dispatch:

jobs:
  extend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run auto_extend.py
        run: |
          pip install -r requirements.txt || true
          python auto_extend.py

      - name: Push update
        run: |
          git config user.name "Zhenzhen Bot"
          git config user.email "bot@zhenzhenmi.com"
          git add .
          git commit -m "🤖 自動加入新撩語" || echo "no changes"
          git push